metadata:
  name: ${project.artifactId}-configmap
data:
  application.properties: |-
    spring.datasource.url=jdbc:mysql://mysql:3306/sampledb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    camel.component.kafka.configuration.brokers=my-cluster-kafka-bootstrap.strimzi.svc:9092
