metadata:
  name: ${project.artifactId}-configmap
data:
  application.properties: |-
    spring.datasource.url=jdbc:mysql://mysql.db.svc:3306/sampledb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    amqphub.amqp10jms.remote-url=amqp://ex-aao-amqp-0-svc.broker.svc:5672
