spec:
  template:
    spec:
      containers:
      - name: ${project.artifactId}
        env:
        - name: SPRING_CONFIG_ADDITIONAL_LOCATION
          value: file:/etc/config/
        - name: AMQPHUB_AMQP10JMS_USERNAME
          valueFrom:
            secretKeyRef:
              name: ex-aao-credentials-secret
              key: AMQ_USER
        - name: AMQPHUB_AMQP10JMS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ex-aao-credentials-secret
              key: AMQ_PASSWORD
        resources:
          requests:
            cpu: "0.5"
          limits:
            cpu: "4.0"
        volumeMounts:
        - name: ${project.artifactId}-configmap-vol
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: ${project.artifactId}-configmap-vol
        configMap:
          name: ${project.artifactId}-configmap
