# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  endpoints:
    web.exposure.include: info,health,camelroutes
  endpoint:
    health:
      enabled: true
    camelroutes:
      enabled: true
      read-only: true

# Spring Boot
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampledb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Abcd1234
  sql:
    init:
      enabled: true
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      continue-on-error: true

# AMQPHub
amqphub:
  amqp10jms:
    pool:
      enabled: true
    remote-url: amqp://localhost:5672
    #username: admin
    #password: admin

# Camel Spring Boot
camel:
  springboot:
    name: camel-processor

# Logging
logging:
  config: classpath:logback.xml
  level:
    com.redhat.examples: INFO
